// Generated by Apple Swift version 6.2 effective-5.10 (swiftlang-6.2.0.19.9 clang-1700.3.19.1)
#ifndef STREAMHAVEN_SWIFT_H
#define STREAMHAVEN_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFoundation;
@import CoreData;
@import CoreMedia;
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="StreamHaven",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSEntityDescription;
@class NSManagedObjectContext;
/// Represents a television channel in the application.
/// This class is a Core Data managed object.
SWIFT_CLASS_NAMED("Channel")
@interface Channel : NSManagedObject
- (void)awakeFromInsert;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class EPGEntry;
@class NSSet;
@interface Channel (SWIFT_EXTENSION(StreamHaven))
/// Adds a single <code>EPGEntry</code> to the <code>epgEntries</code> set.
/// \param value The <code>EPGEntry</code> to add.
///
- (void)addEpgEntriesObject:(EPGEntry * _Nonnull)value;
/// Removes a single <code>EPGEntry</code> from the <code>epgEntries</code> set.
/// \param value The <code>EPGEntry</code> to remove.
///
- (void)removeEpgEntriesObject:(EPGEntry * _Nonnull)value;
/// Adds multiple <code>EPGEntry</code> objects to the <code>epgEntries</code> set.
/// \param values An <code>NSSet</code> of <code>EPGEntry</code> objects to add.
///
- (void)addEpgEntries:(NSSet * _Nonnull)values;
/// Removes multiple <code>EPGEntry</code> objects from the <code>epgEntries</code> set.
/// \param values An <code>NSSet</code> of <code>EPGEntry</code> objects to remove.
///
- (void)removeEpgEntries:(NSSet * _Nonnull)values;
@end

@class ChannelVariant;
@interface Channel (SWIFT_EXTENSION(StreamHaven))
/// Adds a single <code>ChannelVariant</code> to the <code>variants</code> set.
/// \param value The <code>ChannelVariant</code> to add.
///
- (void)addVariantsObject:(ChannelVariant * _Nonnull)value;
/// Removes a single <code>ChannelVariant</code> from the <code>variants</code> set.
/// \param value The <code>ChannelVariant</code> to remove.
///
- (void)removeVariantsObject:(ChannelVariant * _Nonnull)value;
/// Adds multiple <code>ChannelVariant</code> objects to the <code>variants</code> set.
/// \param values An <code>NSSet</code> of <code>ChannelVariant</code> objects to add.
///
- (void)addVariants:(NSSet * _Nonnull)values;
/// Removes multiple <code>ChannelVariant</code> objects from the <code>variants</code> set.
/// \param values An <code>NSSet</code> of <code>ChannelVariant</code> objects to remove.
///
- (void)removeVariants:(NSSet * _Nonnull)values;
@end

@class NSString;
@class NSDate;
@interface Channel (SWIFT_EXTENSION(StreamHaven))
/// Cached count of variants (denormalized for performance).
/// Updated automatically via Core Data derived attribute or manually.
@property (nonatomic) int32_t variantCount;
/// Cached flag indicating if channel has EPG data (denormalized).
@property (nonatomic) BOOL hasEPG;
/// Cached current program title (denormalized, updated periodically).
@property (nonatomic, copy) NSString * _Nullable currentProgramTitle;
/// Timestamp of last EPG update for cache invalidation.
@property (nonatomic, copy) NSDate * _Nullable epgLastUpdated;
@end

@class NSUUID;
@class Favorite;
@interface Channel (SWIFT_EXTENSION(StreamHaven))
/// The URL of the channel’s logo.
@property (nonatomic, copy) NSString * _Nullable logoURL;
/// The name of the channel.
@property (nonatomic, copy) NSString * _Nullable name;
/// The TVG ID used for linking to EPG data (from tvg-id attribute in M3U).
@property (nonatomic, copy) NSString * _Nullable tvgID;
/// A stable UUID string for cross-table references and FTS mapping.
@property (nonatomic, copy) NSString * _Nullable stableID;
/// The unique identifier of the source this channel came from.
@property (nonatomic, copy) NSUUID * _Nullable sourceID;
/// A set of <code>ChannelVariant</code> objects representing different streams or versions of the channel.
@property (nonatomic, strong) NSSet * _Nullable variants;
/// The <code>Favorite</code> object if the channel is marked as a favorite.
@property (nonatomic, strong) Favorite * _Nullable favorite;
/// A set of <code>EPGEntry</code> objects representing the electronic program guide for this channel.
@property (nonatomic, strong) NSSet * _Nullable epgEntries;
@end

/// Represents a specific stream or version of a television channel.
/// This class is a Core Data managed object.
SWIFT_CLASS_NAMED("ChannelVariant")
@interface ChannelVariant : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface ChannelVariant (SWIFT_EXTENSION(StreamHaven))
/// The name of the channel variant (e.g., “HD”, “SD”).
@property (nonatomic, copy) NSString * _Nullable name;
/// The URL of the video stream for this variant.
@property (nonatomic, copy) NSString * _Nullable streamURL;
/// The unique identifier of the source this variant came from.
@property (nonatomic, copy) NSUUID * _Nullable sourceID;
/// The parent <code>Channel</code> object to which this variant belongs.
@property (nonatomic, strong) Channel * _Nullable channel;
@end

/// Represents a downloaded or downloading content item.
/// This class is a Core Data managed object.
SWIFT_CLASS_NAMED("Download")
@interface Download : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class Movie;
@class Episode;
@interface Download (SWIFT_EXTENSION(StreamHaven))
/// The stream URL of the content.
@property (nonatomic, copy) NSString * _Nullable streamURL;
/// The title of the content.
@property (nonatomic, copy) NSString * _Nullable contentTitle;
/// The type of content (movie, episode).
@property (nonatomic, copy) NSString * _Nullable contentType;
/// The download status (queued, downloading, completed, failed, paused).
@property (nonatomic, copy) NSString * _Nullable status;
/// The download progress (0.0 to 1.0).
@property (nonatomic) float progress;
/// The local file path once downloaded.
@property (nonatomic, copy) NSString * _Nullable filePath;
/// The file size in bytes.
@property (nonatomic) int64_t fileSize;
/// The date when the download completed.
@property (nonatomic, copy) NSDate * _Nullable downloadedAt;
/// The expiration date for the download.
@property (nonatomic, copy) NSDate * _Nullable expiresAt;
/// The thumbnail URL.
@property (nonatomic, copy) NSString * _Nullable thumbnailURL;
/// The IMDb ID for matching.
@property (nonatomic, copy) NSString * _Nullable imdbID;
/// The <code>Movie</code> object if the download is for a movie.
@property (nonatomic, strong) Movie * _Nullable movie;
/// The <code>Episode</code> object if the download is for an episode.
@property (nonatomic, strong) Episode * _Nullable episode;
@end

/// Manages persistent downloads of HLS content for offline playback.
/// Uses AVAssetDownloadURLSession for HLS streaming downloads.
SWIFT_CLASS("_TtC11StreamHaven15DownloadManager")
@interface DownloadManager : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSURLSession;
@class AVAssetDownloadTask;
@class NSURL;
@class NSValue;
@class NSURLSessionTask;
SWIFT_AVAILABILITY(macos,introduced=11.0) SWIFT_AVAILABILITY(ios,introduced=15.0)
@interface DownloadManager (SWIFT_EXTENSION(StreamHaven)) <AVAssetDownloadDelegate>
- (void)URLSession:(NSURLSession * _Nonnull)session assetDownloadTask:(AVAssetDownloadTask * _Nonnull)assetDownloadTask didFinishDownloadingToURL:(NSURL * _Nonnull)location;
- (void)URLSession:(NSURLSession * _Nonnull)session assetDownloadTask:(AVAssetDownloadTask * _Nonnull)assetDownloadTask didLoadTimeRange:(CMTimeRange)timeRange totalTimeRangesLoaded:(NSArray<NSValue *> * _Nonnull)loadedTimeRanges timeRangeExpectedToLoad:(CMTimeRange)expectedTimeRange;
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task didCompleteWithError:(NSError * _Nullable)error;
@end

/// Represents an EPG (Electronic Program Guide) entry in the application.
/// This class is a Core Data managed object.
SWIFT_CLASS_NAMED("EPGEntry")
@interface EPGEntry : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface EPGEntry (SWIFT_EXTENSION(StreamHaven))
/// The category or genre of the program (e.g., “Sports”, “News”, “Drama”).
@property (nonatomic, copy) NSString * _Nullable category;
/// A detailed description of the program.
@property (nonatomic, copy) NSString * _Nullable descriptionText;
/// The end time of the program.
@property (nonatomic, copy) NSDate * _Nullable endTime;
/// The start time of the program.
@property (nonatomic, copy) NSDate * _Nullable startTime;
/// The title of the program.
@property (nonatomic, copy) NSString * _Nullable title;
/// The channel this EPG entry belongs to.
@property (nonatomic, strong) Channel * _Nullable channel;
@end

@class NSXMLParser;
/// A parser for processing XMLTV format EPG data and importing it into Core Data.
SWIFT_CLASS("_TtC11StreamHaven9EPGParser")
@interface EPGParser : NSObject <NSXMLParserDelegate>
- (void)parser:(NSXMLParser * _Nonnull)parser didStartElement:(NSString * _Nonnull)elementName namespaceURI:(NSString * _Nullable)namespaceURI qualifiedName:(NSString * _Nullable)qName attributes:(NSDictionary<NSString *, NSString *> * _Nonnull)attributeDict;
- (void)parser:(NSXMLParser * _Nonnull)parser foundCharacters:(NSString * _Nonnull)string;
- (void)parser:(NSXMLParser * _Nonnull)parser didEndElement:(NSString * _Nonnull)elementName namespaceURI:(NSString * _Nullable)namespaceURI qualifiedName:(NSString * _Nullable)qName;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Represents a single episode of a television series.
/// This class is a Core Data managed object.
SWIFT_CLASS_NAMED("Episode")
@interface Episode : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class Season;
@class WatchHistory;
@interface Episode (SWIFT_EXTENSION(StreamHaven))
/// The number of the episode within a season.
@property (nonatomic) int16_t episodeNumber;
/// A short summary or description of the episode.
@property (nonatomic, copy) NSString * _Nullable summary;
/// The title of the episode.
@property (nonatomic, copy) NSString * _Nullable title;
/// The URL of the video stream for this episode.
@property (nonatomic, copy) NSString * _Nullable streamURL;
/// The start time of the intro in seconds (0 if unknown).
@property (nonatomic) double introStartTime;
/// The end time of the intro in seconds (0 if unknown).
@property (nonatomic) double introEndTime;
/// The start time of the credits in seconds (0 if unknown).
@property (nonatomic) double creditStartTime;
/// Whether intro timing data has been fetched and stored.
@property (nonatomic) BOOL hasIntroData;
/// The parent <code>Season</code> object to which this episode belongs.
@property (nonatomic, strong) Season * _Nullable season;
/// The <code>WatchHistory</code> object if the episode has been watched.
@property (nonatomic, strong) WatchHistory * _Nullable watchHistory;
@end

/// Represents a favorite item (movie, series, or channel) for a user profile.
/// This class is a Core Data managed object.
SWIFT_CLASS_NAMED("Favorite")
@interface Favorite : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class Profile;
@class Series;
@interface Favorite (SWIFT_EXTENSION(StreamHaven))
/// The date when the item was marked as a favorite.
@property (nonatomic, copy) NSDate * _Nullable favoritedDate;
/// CloudKit record name for sync tracking.
@property (nonatomic, copy) NSString * _Nullable cloudKitRecordName;
/// Last modification timestamp for conflict resolution.
@property (nonatomic, copy) NSDate * _Nullable modifiedAt;
/// The <code>Profile</code> to which this favorite belongs.
@property (nonatomic, strong) Profile * _Nullable profile;
/// The <code>Movie</code> object if the favorite is a movie.
@property (nonatomic, strong) Movie * _Nullable movie;
/// The <code>Series</code> object if the favorite is a series.
@property (nonatomic, strong) Series * _Nullable series;
/// The <code>Channel</code> object if the favorite is a channel.
@property (nonatomic, strong) Channel * _Nullable channel;
@end

/// Represents a movie in the application.
/// This class is a Core Data managed object.
SWIFT_CLASS_NAMED("Movie")
@interface Movie : NSManagedObject
- (void)awakeFromInsert;
- (void)willSave;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface Movie (SWIFT_EXTENSION(StreamHaven))
/// Cached flag for whether movie has been watched (denormalized).
@property (nonatomic) BOOL hasBeenWatched;
/// Cached watch progress percentage (0-100, denormalized).
@property (nonatomic) int16_t watchProgressPercent;
/// Cached flag for favorite status (denormalized).
@property (nonatomic) BOOL isFavorite;
/// Last watched timestamp (denormalized from WatchHistory).
@property (nonatomic, copy) NSDate * _Nullable lastWatchedDate;
@end

@interface Movie (SWIFT_EXTENSION(StreamHaven))
/// The URL of the movie’s poster image.
@property (nonatomic, copy) NSString * _Nullable posterURL;
/// The content rating of the movie (e.g., “PG-13”, “R”).
@property (nonatomic, copy) NSString * _Nullable rating;
/// The release date of the movie.
@property (nonatomic, copy) NSDate * _Nullable releaseDate;
/// A short summary or description of the movie.
@property (nonatomic, copy) NSString * _Nullable summary;
/// Comma-separated genre list for the movie.
@property (nonatomic, copy) NSString * _Nullable genres;
/// The URL of the video stream for this movie.
@property (nonatomic, copy) NSString * _Nullable streamURL;
/// The URL of a preview or trailer clip for hover playback.
@property (nonatomic, copy) NSString * _Nullable previewURL;
/// The title of the movie.
@property (nonatomic, copy) NSString * _Nullable title;
/// The IMDb ID of the movie (e.g., “tt1234567”).
@property (nonatomic, copy) NSString * _Nullable imdbID;
/// A stable UUID string for cross-table references and FTS mapping.
@property (nonatomic, copy) NSString * _Nullable stableID;
/// The unique identifier of the source this movie came from.
@property (nonatomic, copy) NSUUID * _Nullable sourceID;
/// The <code>WatchHistory</code> object if the movie has been watched.
@property (nonatomic, strong) WatchHistory * _Nullable watchHistory;
/// The <code>Favorite</code> object if the movie is marked as a favorite.
@property (nonatomic, strong) Favorite * _Nullable favorite;
@end

@class NSURLRequest;
@class NSCachedURLResponse;
@protocol NSURLProtocolClient;
/// A URLProtocol that logs request/response details and timing for debugging and performance monitoring.
SWIFT_CLASS("_TtC11StreamHaven24NetworkLoggerURLProtocol")
@interface NetworkLoggerURLProtocol : NSURLProtocol
+ (BOOL)canInitWithRequest:(NSURLRequest * _Nonnull)request SWIFT_WARN_UNUSED_RESULT;
+ (NSURLRequest * _Nonnull)canonicalRequestForRequest:(NSURLRequest * _Nonnull)request SWIFT_WARN_UNUSED_RESULT;
- (void)startLoading;
- (void)stopLoading;
- (nonnull instancetype)initWithRequest:(NSURLRequest * _Nonnull)request cachedResponse:(NSCachedURLResponse * _Nullable)cachedResponse client:(id <NSURLProtocolClient> _Nullable)client OBJC_DESIGNATED_INITIALIZER;
@end

/// A class for managing media playback.
SWIFT_CLASS("_TtC11StreamHaven15PlaybackManager")
@interface PlaybackManager : NSObject
- (void)observeValueForKeyPath:(NSString * _Nullable)keyPath ofObject:(id _Nullable)object change:(NSDictionary<NSKeyValueChangeKey, id> * _Nullable)change context:(void * _Nullable)context;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Represents the cached data of a playlist.
/// This class is a Core Data managed object.
SWIFT_CLASS_NAMED("PlaylistCache")
@interface PlaylistCache : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface PlaylistCache (SWIFT_EXTENSION(StreamHaven))
/// The local file path where the playlist content is cached.
@property (nonatomic, copy) NSString * _Nullable filePath;
/// The date when the playlist was last refreshed.
@property (nonatomic, copy) NSDate * _Nullable lastRefreshed;
/// The URL of the playlist.
@property (nonatomic, copy) NSString * _Nullable url;
/// The URL of the EPG (Electronic Program Guide) source for this playlist.
@property (nonatomic, copy) NSString * _Nullable epgURL;
/// The unique identifier of the source this cache belongs to.
@property (nonatomic, copy) NSUUID * _Nullable sourceID;
@end

/// Represents a playlist source (M3U or Xtream Codes) for a user profile.
/// This class is a Core Data managed object.
SWIFT_CLASS_NAMED("PlaylistSource")
@interface PlaylistSource : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface PlaylistSource (SWIFT_EXTENSION(StreamHaven))
/// Unique identifier for the source.
@property (nonatomic, copy) NSUUID * _Nullable sourceID;
/// User-defined name for the source.
@property (nonatomic, copy) NSString * _Nullable name;
/// Type of source: “m3u” or “xtream”.
@property (nonatomic, copy) NSString * _Nullable sourceType;
/// URL for M3U playlists or Xtream Codes server.
@property (nonatomic, copy) NSString * _Nullable url;
/// Username for Xtream Codes authentication.
@property (nonatomic, copy) NSString * _Nullable username;
/// Password for Xtream Codes authentication (stored securely in Keychain via manager).
@property (nonatomic, copy) NSString * _Nullable password;
/// Whether this source is currently active.
@property (nonatomic) BOOL isActive;
/// Display order for sorting sources.
@property (nonatomic) int32_t displayOrder;
/// Date when the source was created.
@property (nonatomic, copy) NSDate * _Nullable createdAt;
/// Date when the source was last refreshed.
@property (nonatomic, copy) NSDate * _Nullable lastRefreshed;
/// Last error message from loading this source (if any).
@property (nonatomic, copy) NSString * _Nullable lastError;
/// JSON metadata for additional source configuration.
@property (nonatomic, copy) NSString * _Nullable metadata;
/// The profile that owns this source.
@property (nonatomic, strong) Profile * _Nullable profile;
@end

/// Represents a user profile in the application.
/// This class is a Core Data managed object.
SWIFT_CLASS_NAMED("Profile")
@interface Profile : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface Profile (SWIFT_EXTENSION(StreamHaven))
/// Adds a single <code>Favorite</code> object to the <code>favorites</code> set.
/// \param value The <code>Favorite</code> to add.
///
- (void)addFavoritesObject:(Favorite * _Nonnull)value;
/// Removes a single <code>Favorite</code> object from the <code>favorites</code> set.
/// \param value The <code>Favorite</code> to remove.
///
- (void)removeFavoritesObject:(Favorite * _Nonnull)value;
/// Adds multiple <code>Favorite</code> objects to the <code>favorites</code> set.
/// \param values An <code>NSSet</code> of <code>Favorite</code> objects to add.
///
- (void)addFavorites:(NSSet * _Nonnull)values;
/// Removes multiple <code>Favorite</code> objects from the <code>favorites</code> set.
/// \param values An <code>NSSet</code> of <code>Favorite</code> objects to remove.
///
- (void)removeFavorites:(NSSet * _Nonnull)values;
@end

@interface Profile (SWIFT_EXTENSION(StreamHaven))
/// Adds a single <code>PlaylistSource</code> object to the <code>playlistSources</code> set.
/// \param value The <code>PlaylistSource</code> to add.
///
- (void)addPlaylistSourcesObject:(PlaylistSource * _Nonnull)value;
/// Removes a single <code>PlaylistSource</code> object from the <code>playlistSources</code> set.
/// \param value The <code>PlaylistSource</code> to remove.
///
- (void)removePlaylistSourcesObject:(PlaylistSource * _Nonnull)value;
/// Adds multiple <code>PlaylistSource</code> objects to the <code>playlistSources</code> set.
/// \param values An <code>NSSet</code> of <code>PlaylistSource</code> objects to add.
///
- (void)addPlaylistSources:(NSSet * _Nonnull)values;
/// Removes multiple <code>PlaylistSource</code> objects from the <code>playlistSources</code> set.
/// \param values An <code>NSSet</code> of <code>PlaylistSource</code> objects to remove.
///
- (void)removePlaylistSources:(NSSet * _Nonnull)values;
@end

@interface Profile (SWIFT_EXTENSION(StreamHaven))
/// Adds a single <code>WatchHistory</code> object to the <code>watchHistory</code> set.
/// \param value The <code>WatchHistory</code> to add.
///
- (void)addWatchHistoryObject:(WatchHistory * _Nonnull)value;
/// Removes a single <code>WatchHistory</code> object from the <code>watchHistory</code> set.
/// \param value The <code>WatchHistory</code> to remove.
///
- (void)removeWatchHistoryObject:(WatchHistory * _Nonnull)value;
/// Adds multiple <code>WatchHistory</code> objects to the <code>watchHistory</code> set.
/// \param values An <code>NSSet</code> of <code>WatchHistory</code> objects to add.
///
- (void)addWatchHistory:(NSSet * _Nonnull)values;
/// Removes multiple <code>WatchHistory</code> objects from the <code>watchHistory</code> set.
/// \param values An <code>NSSet</code> of <code>WatchHistory</code> objects to remove.
///
- (void)removeWatchHistory:(NSSet * _Nonnull)values;
@end

@interface Profile (SWIFT_EXTENSION(StreamHaven))
/// A boolean indicating whether the profile is for an adult.
@property (nonatomic) BOOL isAdult;
/// The name of the profile.
@property (nonatomic, copy) NSString * _Nullable name;
/// CloudKit record name for sync tracking.
@property (nonatomic, copy) NSString * _Nullable cloudKitRecordName;
/// Last modification timestamp for conflict resolution.
@property (nonatomic, copy) NSDate * _Nullable modifiedAt;
/// Source viewing mode: “combined” (merge all sources) or “single” (view one source at a time).
@property (nonatomic, copy) NSString * _Nullable sourceMode;
/// A set of <code>Favorite</code> objects associated with the profile.
@property (nonatomic, strong) NSSet * _Nullable favorites;
/// A set of <code>WatchHistory</code> objects associated with the profile.
@property (nonatomic, strong) NSSet * _Nullable watchHistory;
/// A set of <code>PlaylistSource</code> objects associated with the profile.
@property (nonatomic, strong) NSSet * _Nullable playlistSources;
@end

/// Represents a season of a television series.
/// This class is a Core Data managed object.
SWIFT_CLASS_NAMED("Season")
@interface Season : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface Season (SWIFT_EXTENSION(StreamHaven))
/// Adds a single <code>Episode</code> object to the <code>episodes</code> set.
/// \param value The <code>Episode</code> to add.
///
- (void)addEpisodesObject:(Episode * _Nonnull)value;
/// Removes a single <code>Episode</code> object from the <code>episodes</code> set.
/// \param value The <code>Episode</code> to remove.
///
- (void)removeEpisodesObject:(Episode * _Nonnull)value;
/// Adds multiple <code>Episode</code> objects to the <code>episodes</code> set.
/// \param values An <code>NSSet</code> of <code>Episode</code> objects to add.
///
- (void)addEpisodes:(NSSet * _Nonnull)values;
/// Removes multiple <code>Episode</code> objects from the <code>episodes</code> set.
/// \param values An <code>NSSet</code> of <code>Episode</code> objects to remove.
///
- (void)removeEpisodes:(NSSet * _Nonnull)values;
@end

@interface Season (SWIFT_EXTENSION(StreamHaven))
/// The number of the season.
@property (nonatomic) int16_t seasonNumber;
/// A short summary or description of the season.
@property (nonatomic, copy) NSString * _Nullable summary;
/// A set of <code>Episode</code> objects belonging to this season.
@property (nonatomic, strong) NSSet * _Nullable episodes;
/// The parent <code>Series</code> object to which this season belongs.
@property (nonatomic, strong) Series * _Nullable series;
@end

/// Represents a television series in the application.
/// This class is a Core Data managed object.
SWIFT_CLASS_NAMED("Series")
@interface Series : NSManagedObject
- (void)awakeFromInsert;
- (void)willSave;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface Series (SWIFT_EXTENSION(StreamHaven))
/// Adds a single <code>Season</code> object to the <code>seasons</code> set.
/// \param value The <code>Season</code> to add.
///
- (void)addSeasonsObject:(Season * _Nonnull)value;
/// Removes a single <code>Season</code> object from the <code>seasons</code> set.
/// \param value The <code>Season</code> to remove.
///
- (void)removeSeasonsObject:(Season * _Nonnull)value;
/// Adds multiple <code>Season</code> objects to the <code>seasons</code> set.
/// \param values An <code>NSSet</code> of <code>Season</code> objects to add.
///
- (void)addSeasons:(NSSet * _Nonnull)values;
/// Removes multiple <code>Season</code> objects from the <code>seasons</code> set.
/// \param values An <code>NSSet</code> of <code>Season</code> objects to remove.
///
- (void)removeSeasons:(NSSet * _Nonnull)values;
@end

@interface Series (SWIFT_EXTENSION(StreamHaven))
/// Cached total episode count across all seasons (denormalized).
@property (nonatomic) int32_t totalEpisodeCount;
/// Cached season count (denormalized).
@property (nonatomic) int16_t seasonCount;
/// Cached flag for favorite status (denormalized).
@property (nonatomic) BOOL isFavorite;
/// Cached unwatched episode count (denormalized).
@property (nonatomic) int32_t unwatchedEpisodeCount;
@end

@interface Series (SWIFT_EXTENSION(StreamHaven))
/// The URL of the series’ poster image.
@property (nonatomic, copy) NSString * _Nullable posterURL;
/// The content rating of the series (e.g., “PG-13”, “R”).
@property (nonatomic, copy) NSString * _Nullable rating;
/// The release date of the series.
@property (nonatomic, copy) NSDate * _Nullable releaseDate;
/// A short summary or description of the series.
@property (nonatomic, copy) NSString * _Nullable summary;
/// Comma-separated genre list for the series.
@property (nonatomic, copy) NSString * _Nullable genres;
/// The title of the series.
@property (nonatomic, copy) NSString * _Nullable title;
/// The URL of a preview or trailer clip for hover playback.
@property (nonatomic, copy) NSString * _Nullable previewURL;
/// A stable UUID string for cross-table references and FTS mapping.
@property (nonatomic, copy) NSString * _Nullable stableID;
/// The unique identifier of the source this series came from.
@property (nonatomic, copy) NSUUID * _Nullable sourceID;
/// A set of <code>Season</code> objects belonging to this series.
@property (nonatomic, strong) NSSet * _Nullable seasons;
/// The <code>Favorite</code> object if the series is marked as a favorite.
@property (nonatomic, strong) Favorite * _Nullable favorite;
@end

SWIFT_CLASS_NAMED("StreamCache")
@interface StreamCache : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface StreamCache (SWIFT_EXTENSION(StreamHaven))
@property (nonatomic, copy) NSString * _Nonnull streamURL;
@property (nonatomic, copy) NSDate * _Nonnull cachedAt;
@property (nonatomic, copy) NSDate * _Nonnull lastAccessed;
@property (nonatomic, copy) NSDate * _Nonnull expiresAt;
@property (nonatomic, copy) NSString * _Nonnull cacheIdentifier;
@end

SWIFT_CLASS_NAMED("UpNextQueueItem")
@interface UpNextQueueItem : NSManagedObject
@property (nonatomic, copy) NSString * _Nonnull contentID;
@property (nonatomic, copy) NSString * _Nonnull contentType;
@property (nonatomic, copy) NSDate * _Nonnull addedAt;
@property (nonatomic) int32_t position;
@property (nonatomic) BOOL autoAdded;
@property (nonatomic, strong) Profile * _Nullable profile;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

/// Represents the watch history for a movie or episode.
/// This class is a Core Data managed object.
SWIFT_CLASS_NAMED("WatchHistory")
@interface WatchHistory : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface WatchHistory (SWIFT_EXTENSION(StreamHaven))
/// The watch progress as a percentage (0.0 to 1.0).
@property (nonatomic) float progress;
/// The date when the item was last watched.
@property (nonatomic, copy) NSDate * _Nullable watchedDate;
/// CloudKit record name for sync tracking.
@property (nonatomic, copy) NSString * _Nullable cloudKitRecordName;
/// Last modification timestamp for conflict resolution.
@property (nonatomic, copy) NSDate * _Nullable modifiedAt;
/// The <code>Profile</code> to which this watch history belongs.
@property (nonatomic, strong) Profile * _Nullable profile;
/// The <code>Movie</code> object if the watch history is for a movie.
@property (nonatomic, strong) Movie * _Nullable movie;
/// The <code>Episode</code> object if the watch history is for an episode.
@property (nonatomic, strong) Episode * _Nullable episode;
@end

SWIFT_CLASS_NAMED("Watchlist")
@interface Watchlist : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class WatchlistItem;
@interface Watchlist (SWIFT_EXTENSION(StreamHaven))
- (void)addItemsObject:(WatchlistItem * _Nonnull)value;
- (void)removeItemsObject:(WatchlistItem * _Nonnull)value;
- (void)addItems:(NSSet * _Nonnull)values;
- (void)removeItems:(NSSet * _Nonnull)values;
@end

@interface Watchlist (SWIFT_EXTENSION(StreamHaven))
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSDate * _Nonnull createdAt;
@property (nonatomic, copy) NSDate * _Nonnull updatedAt;
@property (nonatomic, copy) NSString * _Nonnull icon;
@property (nonatomic, strong) Profile * _Nonnull profile;
@property (nonatomic, strong) NSSet * _Nullable items;
@end

SWIFT_CLASS_NAMED("WatchlistItem")
@interface WatchlistItem : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface WatchlistItem (SWIFT_EXTENSION(StreamHaven))
@property (nonatomic, copy) NSString * _Nonnull contentID;
@property (nonatomic, copy) NSString * _Nonnull contentType;
@property (nonatomic, copy) NSDate * _Nonnull addedAt;
@property (nonatomic) int32_t position;
@property (nonatomic, strong) Watchlist * _Nonnull watchlist;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif
